# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SquashMarker' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SquashMarker
  pod 'FontAwesome.swift', '~> 1.3'

  target 'SquashMarkerTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'FontAwesome.swift', '~> 1.3'
  end

  target 'SquashMarkerUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
