# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SquashMarker' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

def common_pods
pod 'FontAwesome.swift', '~> 1.3'
pod 'SwiftLint'
end

  # Pods for SquashMarker
    common_pods

  target 'SquashMarkerTests' do
    inherit! :search_paths
    # Pods for testing
    common_pods
  end

  target 'SquashMarkerUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
